### ISSUE TITLE
Tipbetigi dili tanimlama dizecleri

### ISSUE THREAD

**Issue by onatm** [ilgilenio/Otag#7]
Merhaba,

Elinize, emeginize, gonlunuze saglik. Tipbetigi dili tanimlama dizeclerini eklemeyi dusunuyor musunuz?

Tesekkurler.

**Comment by alpeer** [comment]
Esenlikler,
Typescript hakkında düşüncelerimiz olumsuz.
Bize göre Typescript kullanmak M******** aksanıyla ...
